theme: jekyll-theme-architect
title: "The Looter's WeatherApp"
description: "Windows 10 application to monitor the current weather in two locations across the globe"
show_downloads: "true"
owner_url : "https://skipmcgee.github.io"
stable_zip_url : "https://github.com/skipmcgee/WeatherApp/archive/v1.0.1.zip"
gtag.js : "G-MC8X173TB1"
google_analytics : "G-MC8X173TB1"
url: "https://skipmcgee.github.io/WeatherApp"
plugins :
  - jekyll-paginate
  - jekyll-sitemap
author :
  name : "Skip McGee"
  email : "davidfranklinmcgee@gmail.com"
  github : "skipmcgee"
